# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: browser_copilot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "browser_copilot.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15\x62rowser_copilot.proto\x12\x0f\x62rowser_copilot"m\n\x12SendMessageRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x32\n\x0cmessage_type\x18\x02 \x01(\x0e\x32\x1c.browser_copilot.MessageType\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t"^\n\x0fMessageResponse\x12\x0e\n\x04text\x18\x01 \x01(\tH\x00\x12/\n\x05image\x18\x02 \x01(\x0b\x32\x1e.browser_copilot.ImageResponseH\x00\x42\n\n\x08response"7\n\rImageResponse\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t*+\n\x0bMessageType\x12\x08\n\x04TEXT\x10\x00\x12\t\n\x05IMAGE\x10\x01\x12\x07\n\x03PDF\x10\x02\x32o\n\x15\x42rowserCopilotService\x12V\n\x0bSendMessage\x12#.browser_copilot.SendMessageRequest\x1a .browser_copilot.MessageResponse0\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "browser_copilot_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_MESSAGETYPE"]._serialized_start = 306
    _globals["_MESSAGETYPE"]._serialized_end = 349
    _globals["_SENDMESSAGEREQUEST"]._serialized_start = 42
    _globals["_SENDMESSAGEREQUEST"]._serialized_end = 151
    _globals["_MESSAGERESPONSE"]._serialized_start = 153
    _globals["_MESSAGERESPONSE"]._serialized_end = 247
    _globals["_IMAGERESPONSE"]._serialized_start = 249
    _globals["_IMAGERESPONSE"]._serialized_end = 304
    _globals["_BROWSERCOPILOTSERVICE"]._serialized_start = 351
    _globals["_BROWSERCOPILOTSERVICE"]._serialized_end = 462
# @@protoc_insertion_point(module_scope)
