# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

import browser_copilot_pb2 as browser__copilot__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in browser_copilot_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class BrowserCopilotServiceStub(object):
    """Service definition"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_stream(
            "/browser_copilot.BrowserCopilotService/SendMessage",
            request_serializer=browser__copilot__pb2.SendMessageRequest.SerializeToString,
            response_deserializer=browser__copilot__pb2.MessageResponse.FromString,
            _registered_method=True,
        )


class BrowserCopilotServiceServicer(object):
    """Service definition"""

    def SendMessage(self, request, context):
        """Server-side streaming RPC to send messages and receive responses"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_BrowserCopilotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SendMessage": grpc.unary_stream_rpc_method_handler(
            servicer.SendMessage,
            request_deserializer=browser__copilot__pb2.SendMessageRequest.FromString,
            response_serializer=browser__copilot__pb2.MessageResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "browser_copilot.BrowserCopilotService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "browser_copilot.BrowserCopilotService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class BrowserCopilotService(object):
    """Service definition"""

    @staticmethod
    def SendMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/browser_copilot.BrowserCopilotService/SendMessage",
            browser__copilot__pb2.SendMessageRequest.SerializeToString,
            browser__copilot__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
